services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "user_name"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "quiz"
    networks:
      - db-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_name"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  db-net:
    driver: bridge