services:

  eureka:
    image: simon1999/50fragen:eureka-dev
    networks:
      - 50Fragen
    ports:
      - 8761:8761

  frontend:
    image: simon1999/50fragen:frontend-dev
    networks:
      - 50Fragen
    environment:
      - EUREKA_SERVER=http://eureka:8761/eureka
      - SERVER_PORT=8081
    ports:
      - 8081:8081
    depends_on:
      - eureka

  quiz-session:
    image: simon1999/50fragen:quiz-session-dev
    environment:
      - PORT=8082
      - HOST_IP=quiz-session
      - EUREKA_HOST=http://eureka
      - EUREKA_PORT=8761
    networks:
      - 50Fragen
    ports:
      - 8082:8082
    depends_on:
      - eureka

  quiz-database:
    image: simon1999/50fragen:quiz-database-dev
    networks:
      - 50Fragen
    environment:
      - SERVER_PORT=8083
      - EUREKA_SERVER=http://eureka:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://quiz-database:5432/quiz
      - SPRING_DATASOURCE_USERNAME=user_name
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8083:8083
    depends_on:
      - eureka

  gateway:
    image: simon1999/50fragen:gateway-dev
    ports:
      - 8080:8080
    networks:
      - 50Fragen
    environment:
      - EUREKA_SERVER=http://eureka:8761/eureka
    depends_on:
      - eureka
      - frontend
      - quiz-session


networks:
  50Fragen:
    driver: bridge
