services:

  eureka:
    container_name: eureka
    build:
      context: eureka
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - 50Fragen

  quiz-session:
    container_name: quiz-session
    build:
      context: quiz-session
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - 50Fragen

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - 50Fragen

  quiz-database:
    container_name: quiz-database
    build:
      context: quiz-database
      dockerfile: Dockerfile
    networks:
        - 50Fragen
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://quiz-database:5432/quiz
        - SPRING_DATASOURCE_USERNAME=user_name
        - SPRING_DATASOURCE_PASSWORD=password
        - EUREKA_SERVER=http://eureka:8761/eureka

  gateway:
    container_name: gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - 50Fragen
    depends_on:
      - eureka


networks:
  50Fragen:
    driver: bridge
