services:

  eureka:
    image: simon1999/50fragen:eureka-dev
    networks:
      - 50Fragen

  frontend:
    image: simon1999/50fragen:frontend-dev
    networks:
      - 50Fragen
    environment:
      - EUREKA_SERVER=http://eureka:8761/eureka

  quiz-session:
    image: simon1999/50fragen:quiz-session-dev
    environment:
      - PORT=4000
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
    networks:
      - 50Fragen

  quiz-database:
    image: simon1999/50fragen:quiz-database-dev
    networks:
      - 50Fragen
    environment:
      - EUREKA_SERVER=http://eureka:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://quiz-database:5432/quiz
      - SPRING_DATASOURCE_USERNAME=user_name
      - SPRING_DATASOURCE_PASSWORD=password

  gateway:
    image: simon1999/50fragen:gateway-dev
    ports:
      - 8080:8080
    networks:
      - 50Fragen
    environment:
      - EUREKA_SERVER=http://eureka:8761/eureka
    depends_on:
      - eureka


networks:
  50Fragen:
    driver: bridge
