server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: quiz-session-route
          uri:  lb://quiz-session-service
          predicates:
            - Path=/quiz-session/**
          filters:
              - StripPrefix=1
        - id: frontend-route
          uri: lb://frontend
          predicates:
            - Path=/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true
