spring:
  datasource:
    url: jdbc:postgresql://quiz-postgres:5432/quiz
    username: user_name
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # or none/validate/your choice

server:
  port: 8083