spring:
  application:
    name: quiz-database
server:
  port: ${SERVER_PORT:8010} # needed, as every microservice needs to run on different port
  error:
    include-message: always
    include-binding-errors: always
eureka :
  client :
    serviceUrl :
      defaultZone : ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true