spring:
  application:
    name: quiz-database
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/quiz}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:test}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT:8010} # needed, as every microservice needs to run on different port
  error:
    include-message: always
    include-binding-errors: always
eureka :
  client :
    serviceUrl :
      defaultZone : ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE