spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/my_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:test}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update